# ============================================================================
#  CrossySdkUnrealSamp — convenience Makefile
#
#  Group 1: SDK plugin management (Phase 1)
#  Group 2: Build / device automation (Phase 4; placeholders for now)
#
#  Environment:
#    GITHUB_TOKEN  OPTIONAL. The default registry repo defined in
#                  crossx-plugins.json (to-nexus/crossy-sdk-unreal-sample) is
#                  public, so sdk-install / sdk-update work anonymously out of
#                  the box. Provide a token only if you need to:
#                    - bypass GitHub's 60/hr anonymous rate limit (shared CI
#                      runners), or
#                    - point the registry at a private repo.
#
#                  When needed, it can be provided via either:
#                    (a) shell export:  export GITHUB_TOKEN=...
#                    (b) local .env:    echo 'GITHUB_TOKEN=...' > .env
#                        (.env is .gitignore'd; this Makefile auto-loads it.)
# ============================================================================

SHELL := /usr/bin/env bash
.ONESHELL:
.DEFAULT_GOAL := help

# Auto-load `.env` (and `.env.local` override) — used for the optional
# GITHUB_TOKEN as well as any future per-developer overrides. `export`
# forwards loaded variables into recipe subshells.
ifneq (,$(wildcard .env))
    include .env
    export
endif
ifneq (,$(wildcard .env.local))
    include .env.local
    export
endif

MANIFEST := crossx-plugins.json
LOCK     := crossx-plugins.lock.json

# ----------- build / packaging variables ------------------------------------
#
# Override any of these on the command line or in `.env`, e.g.:
#   make ios UE_ROOT="/Applications/Unreal Engine 5.7"
#   make android ANDROID_PACKAGE=com.example.dapp
# ---------------------------------------------------------------------------

PROJECT_DIR    := $(shell pwd)
PROJECT_NAME   := CrossySdkUnrealSamp
PROJECT        := $(PROJECT_DIR)/$(PROJECT_NAME).uproject
STAGING        := $(PROJECT_DIR)/Saved/StagedBuilds

# Default UE 5.7 install on macOS. On Windows the value would be something
# like "C:/Program Files/Epic Games/UE_5.7"; in either case point at the
# folder that contains Engine/Build/BatchFiles/.
UE_ROOT        ?= /Users/Shared/Epic Games/UE_5.7
ifeq ($(OS),Windows_NT)
    UAT        := "$(UE_ROOT)/Engine/Build/BatchFiles/RunUAT.bat"
else
    UAT        := "$(UE_ROOT)/Engine/Build/BatchFiles/RunUAT.sh"
endif

CONFIGURATION  ?= Development
ARCHIVE_DIR    := $(PROJECT_DIR)/Saved/Archive

# Android ↔ adb plumbing. ANDROID_PACKAGE / ANDROID_ACTIVITY must match the
# values configured in Config/DefaultEngine.ini; if you change the package
# name there, override these as well.
ANDROID_PACKAGE  ?= com.nexus.crossx.sdk.unrealsample.android
ANDROID_ACTIVITY ?= com.epicgames.unreal.GameActivity
ANDROID_APK      := $(PROJECT_DIR)/Binaries/Android/$(PROJECT_NAME)-arm64.apk

# iOS Xcode workspace generated by Unreal Build Tool.
IOS_XCWORKSPACE := $(PROJECT_DIR)/$(PROJECT_NAME) (Mac).xcworkspace
IOS_INTERMEDIATE_XCODEPROJ := $(PROJECT_DIR)/Intermediate/ProjectFilesIOS/$(PROJECT_NAME) (IOS).xcodeproj

# ----------- help -----------------------------------------------------------

.PHONY: help
help: ## Show this help
	@awk 'BEGIN {FS=":.*##"; printf "\nUsage:\n  make \033[36m<target>\033[0m\n\nTargets:\n"} \
		/^[a-zA-Z0-9_-]+:.*?##/ {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

# ----------- Group 1: SDK plugin management ---------------------------------

.PHONY: sdk-install sdk-update sdk-verify sdk-clean localization-import

sdk-install: ## Install / reconcile plugins per crossx-plugins.json (no token needed for the public default registry)
	@./scripts/install-plugins.sh

sdk-update: ## Bump a single plugin. Ex: make sdk-update name=CROSSxSdkUnrealPlugin version=0.3.0
	@if [[ -z "$(name)" || -z "$(version)" ]]; then \
		echo "usage: make sdk-update name=<PluginName> version=<semver>"; exit 2; \
	fi
	@tmp=$$(mktemp); \
		jq --arg n "$(name)" --arg v "$(version)" '.plugins[$$n] = $$v' $(MANIFEST) > $$tmp && mv $$tmp $(MANIFEST); \
		echo "manifest: $(name) -> $(version)"
	@./scripts/install-plugins.sh

sdk-verify: ## Check installed .uplugin VersionName matches manifest/lock
	@./scripts/install-plugins.sh --verify

sdk-clean: ## Remove ./Plugins/CROSSx* (next sdk-install will re-fetch)
	@rm -rf Plugins/CROSSxSdkUnrealPlugin Plugins/CROSSxWebkitSdkUnrealPlugin
	@echo "cleaned Plugins/CROSSx*"

localization-import: ## Reimport Localization/DT_DappStrings.csv into the cooked DataTable asset
	@./scripts/import-dapp-strings.sh

# ----------- Group 2: build / package / device automation -------------------
#
# These targets wrap Unreal's BuildCookRun (RunUAT) for the three primary
# distribution platforms used by external dApp teams. Each target is one of:
#
#   package-*  : full cook + build + stage + package     -> Saved/StagedBuilds/<plat>
#   archive-*  : same, but copies the final artifact out -> Saved/Archive/<plat>
#   install-*  : push the built artifact to a connected device
#   run-*      : launch the artifact on the device
#   xcode-ios  : open the generated Xcode workspace for manual signing /
#                Archive (App Store / TestFlight uploads still go through
#                Xcode Organizer)
#
# Short aliases (`ios`, `android`, `win64`, `install`, `run`) are kept for
# muscle-memory parity with the SDK repo's Makefile.
# ---------------------------------------------------------------------------

.PHONY: ios ios-rebuild ios-archive ios-cook xcode-ios \
        android android-rebuild android-archive install-android run-android deploy-android \
        win64 win64-archive mac mac-archive \
        package-clean

# ─── iOS ───────────────────────────────────────────────────────────────────

ios: ## iOS full build (cook + build + stage + package) into Saved/StagedBuilds
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=IOS \
		-configuration=$(CONFIGURATION) \
		-cook -build -stage -package \
		-stagingdirectory=$(STAGING) \
		-utf8output

ios-rebuild: ## iOS rebuild: wipe Binaries/Intermediate and re-package
	rm -rf "$(PROJECT_DIR)/Binaries/IOS" "$(PROJECT_DIR)/Intermediate/Build/IOS"
	$(MAKE) ios

ios-archive: ## iOS archive (.ipa) into Saved/Archive/IOS for distribution
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=IOS \
		-configuration=$(CONFIGURATION) \
		-cook -build -stage -package -archive \
		-archivedirectory=$(ARCHIVE_DIR)/IOS \
		-utf8output

ios-cook: ## iOS cook only (debug content cooking issues without packaging)
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=IOS \
		-configuration=$(CONFIGURATION) \
		-cook -skipcookonthefly \
		-utf8output

xcode-ios: ## Open the generated iOS Xcode workspace (for signing / Archive)
	@if [ -d "$(IOS_XCWORKSPACE)" ]; then \
		open "$(IOS_XCWORKSPACE)"; \
	elif [ -d "$(IOS_INTERMEDIATE_XCODEPROJ)" ]; then \
		open "$(IOS_INTERMEDIATE_XCODEPROJ)"; \
	else \
		echo "[err] No Xcode project found yet — run 'make ios' once to generate it."; exit 1; \
	fi

# ─── Android ────────────────────────────────────────────────────────────────

android: ## Android full build (cook + build + stage + package -> .apk)
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=Android \
		-configuration=$(CONFIGURATION) \
		-cook -build -stage -package \
		-stagingdirectory=$(STAGING) \
		-utf8output

android-rebuild: ## Android rebuild (wipe Intermediate first)
	rm -rf "$(PROJECT_DIR)/Binaries/Android" "$(PROJECT_DIR)/Intermediate/Build/Android"
	$(MAKE) android

android-archive: ## Android archive (.apk) into Saved/Archive/Android
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=Android \
		-configuration=$(CONFIGURATION) \
		-cook -build -stage -package -archive \
		-archivedirectory=$(ARCHIVE_DIR)/Android \
		-utf8output

install-android: ## Android: adb install -r the most recent APK
	@command -v adb >/dev/null || { echo "[err] adb not on PATH (install Android Studio platform-tools)"; exit 1; }
	@[ -f "$(ANDROID_APK)" ] || { echo "[err] APK not found at $(ANDROID_APK) — run 'make android' first."; exit 1; }
	adb install -r "$(ANDROID_APK)"

run-android: ## Android: launch the installed app via adb
	@command -v adb >/dev/null || { echo "[err] adb not on PATH"; exit 1; }
	adb shell am start -n $(ANDROID_PACKAGE)/$(ANDROID_ACTIVITY)

deploy-android: android install-android ## Android: build + install to connected device

# Short aliases for parity with CrossySdkUnreal/Makefile.
install: install-android ## Alias for install-android
run:     run-android     ## Alias for run-android

# ─── Win64 / Mac (desktop sanity checks) ───────────────────────────────────

win64: ## Win64 full build into Saved/StagedBuilds/Windows
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=Win64 \
		-configuration=$(CONFIGURATION) \
		-cook -build -stage -package \
		-stagingdirectory=$(STAGING) \
		-utf8output

win64-archive: ## Win64 archive into Saved/Archive/Windows
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=Win64 \
		-configuration=$(CONFIGURATION) \
		-cook -build -stage -package -archive \
		-archivedirectory=$(ARCHIVE_DIR)/Windows \
		-utf8output

mac: ## Mac full build into Saved/StagedBuilds/Mac
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=Mac \
		-configuration=$(CONFIGURATION) \
		-cook -build -stage -package \
		-stagingdirectory=$(STAGING) \
		-utf8output

mac-archive: ## Mac archive (.app) into Saved/Archive/Mac
	$(UAT) BuildCookRun \
		-project=$(PROJECT) \
		-platform=Mac \
		-configuration=$(CONFIGURATION) \
		-cook -build -stage -package -archive \
		-archivedirectory=$(ARCHIVE_DIR)/Mac \
		-utf8output

# ─── Cleanup ───────────────────────────────────────────────────────────────

package-clean: ## Remove staged & archived build outputs (keeps DerivedDataCache)
	rm -rf "$(STAGING)" "$(ARCHIVE_DIR)"
	@echo "cleaned $(STAGING) and $(ARCHIVE_DIR)"
